[build]
  
  command = "hugo --gc --minify -b $URL"
  command = "go run post-update.go"
  
  publish = "public"


[build.environment]
  HUGO_VERSION = "0.121.1"
  

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  HUGO_VERSION = "0.121.1"
  command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy.dev]
  HUGO_VERSION = "0.121.1"
  command = "hugo --gc -b $DEPLOY_PRIME_URL"


[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = "true"
