name: Run Go-Script

on:
  push:
    branches:
      - main  # ou la branche que vous souhaitez surveiller

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23  # mettez à jour avec la version de Go que vous utilisez

    
    - name: Run Go Script
       run: |
        echo "Running Go Script"
        go run post-update.go